/video_reader_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info_cam_back.yaml

/gpu_cam_minimal:
  ros__parameters:
    framerate: 30.0
    image_width: 1920
    image_height: 1080
    camera_info_url: "package://rm_vision_bringup/config/camera_info_cam_back.yaml"
    debug: false
    use_v4l2_buffer_timestamps: true
    timestamp_offset: 0.0
    tsc_offset_ns: 0
    brightness: -64
    contrast: 32
    saturation: 128
    hue: 0
    white_balance_automatic: false
    gamma: 100
    gain: 32
    power_line_frequency: 1
    white_balance_temperature: 4600
    sharpness: 1
    backlight_compensation: 0
    auto_exposure: 1
    exposure_time_absolute: 100
    focus_automatic_continuous: false
    focus_absolute: 0
    nvdec_v4l2_buffer_count: 4
    nvdec_capture_buffer_padding: 2
    nvdec_drop_late_frames: true
    egl_platform: "surfaceless"
    flip: false
    gpu_buffer_pool_size: 8
