image_width: 1920
image_height: 1080
camera_name: camera_3
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1.042317875e+03, 0., 8.52541053e+02,
          0., 1.042665779e+03, 6.87723956e+02,
          0., 0., 1. ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [ -3.2348e-02, 3.0295e-02, -3.942e-03, -1.155e-03, 0. ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1., 0., 0.,
          0., 1., 0.,
          0., 0., 1. ]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1.056039201e+03,    0.    , 8.56100462e+02,   0.,
            0.    , 1.056958417e+03, 6.78860239e+02,   0.,
            0.    ,    0.    ,   1.    ,   0. ]
