camera: hik

odom2camera:
  xyz: "\"0.12 0.06  0.04\""
  rpy: "\"0.0 -0.0  0.0\""

detector_log_level: INFO
tracker_log_level: INFO
serial_log_level: INFO

# 设置启动参数
# true: 读取视频 false: 读取相机
video_play: true
# true: 开启打符 false：关闭打符 非必要保持常开
rune: true
# true: 单计算机测试模式 false: 多计算机协同工作
unit_test: true