/video_reader_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
/serial_driver:
  ros__parameters:
    timestamp_offset: -0.0025
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
/virtual_serial: #虚拟串口
  ros__parameters:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    vision_mode: 1 # 0-outpost 6-guard 7-base 8-rune
    color: 0 # 0:红色 1:蓝色
    has_rune: false
/armor_detector:
  ros__parameters:
    debug: true
    detect_color: 0 #0:red;1:blue

    binary_thres: 60
    light.min_ratio: 0.05
    armor.min_light_ratio: 0.8
    classifier_threshold: 0.95
    ignore_classes: ["negative"]
    
    ai_model_path: "/model/0526.onnx"  # 相对于包的路径
    ai_device: "CPU"  # 可选: CPU, GPU, AUTO
    ai_conf_threshold: 0.65  # 置信度阈值
    ai_nms_threshold: 0.45   # NMS阈值