/video_reader_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
/gpu_cam_minimal:
  ros__parameters:
    # 基础采样设置
    framerate: 30.0                # 目标帧率 (Hz)
    image_width: 1920              # 采集宽度 (px)
    image_height: 1080             # 采集高度 (px)
    camera_info_url: "package://rm_vision_bringup/config/camera_info.yaml"  # 相机标定文件
    debug: false                   # 是否发布额外的 debug 图像

    # V4L2 相机控制
    brightness: 0
    contrast: 32
    saturation: 64
    hue: 0
    white_balance_automatic: true
    gamma: 300
    gain: 32
    power_line_frequency: 1
    white_balance_temperature: 4600
    sharpness: 32
    backlight_compensation: 0
    auto_exposure: 1
    exposure_time_absolute: 100

    # NVDEC 低延迟相关参数
    nvdec_v4l2_buffer_count: 4            # V4L2 缓冲区数量 (>=4 更稳)
    nvdec_capture_buffer_padding: 2       # capture plane 额外缓冲数量
    nvdec_drop_late_frames: true          # 是否丢掉滞后的帧，仅保留最新帧
/virtual_serial: #虚拟串口
  ros__parameters:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    vision_mode: 1 # 0-outpost 6-guard 7-base 8-rune
    color: 0 # 0:红色 1:蓝色
    has_rune: false
/armor_detector:
  ros__parameters:
    debug: true
    detect_color: 0 #0:red;1:blue

    binary_thres: 60
    light.min_ratio: 0.05
    armor.min_light_ratio: 0.8
    classifier_threshold: 0.95
    ignore_classes: ["negative"]
    
    ai_model_path: "/model/0526.engine"  # 相对于包的路径
    ai_device: "GPU"  # 仅支持 GPU (需要 CUDA 支持)
    ai_conf_threshold: 0.65  # 置信度阈值
    ai_nms_threshold: 0.45   # NMS阈值